import Head from "next/head";
import Footer from "../components/footer";
import NavBar from "../components/navbar";

import "../styles/globals.css"

function MyApp({ Component, pageProps }) {
  return (
    <div style={{'width': '100%'}}>
      <Head>
        <title>Núcleo São Paulo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato&family=Montserrat&display=swap"
          rel="stylesheet"
        />
      </Head>
      <NavBar />
      <Component {...pageProps} />
      <Footer></Footer>
    </div>
  );
}

export default MyApp;
